import { describe, it, expect, afterEach } from "vitest";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { compile, build, checkBuild, resolveTargets, VENDOR_TARGETS } from "../src/core/vendor.js";
import { makeProject } from "./fixture.js";

let cleanup = () => {};
afterEach(() => cleanup());

const MANIFEST = `
[scope]
name = "demo"
[[fragment]]
id = "rules"
type = "rule"
path = "rules.md"
[[fragment]]
id = "schema"
type = "knowledge"
path = "schema.sql"
`;
const FILES = [
  { path: "rules.md", content: "# rules\nno any types" },
  { path: "schema.sql", content: "CREATE TABLE t (id INT);" },
];

describe("vendor build", () => {
  it("compiles fragments into a single doc with type sections in order", () => {
    const fx = makeProject(MANIFEST, FILES);
    cleanup = fx.cleanup;
    const doc = compile(fx.loaded); // defaults to Claude
    expect(doc).toContain("# CLAUDE.md");
    expect(doc).toContain("Project memory for **demo**");
    expect(doc).toContain("GENERATED by agenticscope");
    // rules section appears before knowledge section
    expect(doc.indexOf("Rules")).toBeLessThan(doc.indexOf("Reference knowledge"));
    expect(doc).toContain("no any types");
    expect(doc).toContain("CREATE TABLE t");
  });

  it("renders vendor-specific preambles", () => {
    const fx = makeProject(MANIFEST, FILES);
    cleanup = fx.cleanup;
    const cursor = VENDOR_TARGETS.find((t) => t.name === "cursor")!;
    const doc = compile(fx.loaded, cursor);
    // .cursorrules is a plain instruction file — no markdown H1, no CLAUDE.md.
    expect(doc).toContain("You are an AI assistant working on demo");
    expect(doc).not.toContain("# CLAUDE.md");
    expect(doc).toContain("no any types");
  });

  it("writes all vendor target files to disk", () => {
    const fx = makeProject(MANIFEST, FILES);
    cleanup = fx.cleanup;
    const { written } = build(fx.loaded);
    expect(written).toEqual(["CLAUDE.md", "GEMINI.md", "AGENTS.md", ".cursorrules"]);
    for (const f of written) {
      expect(existsSync(join(fx.root, f))).toBe(true);
    }
    expect(readFileSync(join(fx.root, "GEMINI.md"), "utf8")).toContain("# GEMINI.md");
  });

  it("build --target writes only the selected vendors", () => {
    const fx = makeProject(MANIFEST, FILES);
    cleanup = fx.cleanup;
    const { written } = build(fx.loaded, resolveTargets(["cursor", "claude"]));
    expect(written.sort()).toEqual([".cursorrules", "CLAUDE.md"]);
    expect(existsSync(join(fx.root, "GEMINI.md"))).toBe(false);
  });

  it("resolveTargets rejects an unknown vendor", () => {
    expect(() => resolveTargets(["nope"])).toThrow(/Unknown vendor target/);
  });

  it("checkBuild reports missing, then ok after build, then stale after edit", () => {
    const fx = makeProject(MANIFEST, FILES);
    cleanup = fx.cleanup;

    // Nothing built yet → all missing.
    expect(checkBuild(fx.loaded).every((c) => c.status === "missing")).toBe(true);

    // After build → all ok.
    build(fx.loaded);
    expect(checkBuild(fx.loaded).every((c) => c.status === "ok")).toBe(true);

    // Tamper with one generated file → that one is stale, the rest ok.
    writeFileSync(join(fx.root, "CLAUDE.md"), "hand-edited, now drifted", "utf8");
    const after = checkBuild(fx.loaded);
    expect(after.find((c) => c.file === "CLAUDE.md")!.status).toBe("stale");
    expect(after.filter((c) => c.status === "ok").length).toBe(VENDOR_TARGETS.length - 1);
  });
});
