import { describe, it, expect, afterEach } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { compile, build } from "../src/core/vendor.js";
import { makeProject } from "./fixture.js";

let cleanup = () => {};
afterEach(() => cleanup());

const MANIFEST = `
[scope]
name = "demo"
[[fragment]]
id = "rules"
type = "rule"
path = "rules.md"
[[fragment]]
id = "schema"
type = "knowledge"
path = "schema.sql"
`;
const FILES = [
  { path: "rules.md", content: "# rules\nno any types" },
  { path: "schema.sql", content: "CREATE TABLE t (id INT);" },
];

describe("vendor build", () => {
  it("compiles fragments into a single doc with type sections in order", () => {
    const fx = makeProject(MANIFEST, FILES);
    cleanup = fx.cleanup;
    const doc = compile(fx.loaded);
    expect(doc).toContain("# Agent context for demo");
    expect(doc).toContain("GENERATED by agenticscope");
    // rules section appears before knowledge section
    expect(doc.indexOf("Rules")).toBeLessThan(doc.indexOf("Reference knowledge"));
    expect(doc).toContain("no any types");
    expect(doc).toContain("CREATE TABLE t");
  });

  it("writes all vendor target files to disk", () => {
    const fx = makeProject(MANIFEST, FILES);
    cleanup = fx.cleanup;
    const { written } = build(fx.loaded);
    expect(written).toEqual(["CLAUDE.md", "GEMINI.md", "AGENTS.md", ".cursorrules"]);
    for (const f of written) {
      const p = join(fx.root, f);
      expect(existsSync(p)).toBe(true);
      expect(readFileSync(p, "utf8")).toContain("Agent context for demo");
    }
  });
});
