import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { Fragment } from "./types.js";
import type { LoadedManifest } from "./manifest.js";

export interface VendorTarget {
  /** Output filename, relative to project root. */
  file: string;
  label: string;
}

/** Vendor files agenticscope can compile the .scope/ source into. */
export const VENDOR_TARGETS: VendorTarget[] = [
  { file: "CLAUDE.md", label: "Claude" },
  { file: "GEMINI.md", label: "Gemini" },
  { file: "AGENTS.md", label: "OpenAI / Codex" },
  { file: ".cursorrules", label: "Cursor" },
];

const ORDER: Fragment["type"][] = ["rule", "persona", "spec", "knowledge"];
const HEADINGS: Record<Fragment["type"], string> = {
  rule: "Rules (always apply)",
  persona: "Persona",
  spec: "Active specs",
  knowledge: "Reference knowledge",
};

/** Compile a manifest's fragments into a single vendor-agnostic markdown doc. */
export function compile(loaded: LoadedManifest): string {
  const { manifest, root } = loaded;
  const name = manifest.scope.name ?? "this project";
  const lines: string[] = [
    `# Agent context for ${name}`,
    "",
    "<!-- GENERATED by agenticscope. Do not edit by hand. Edit .scope/ + agenticscope.toml, then run `agenticscope build`. -->",
    "",
  ];

  for (const type of ORDER) {
    const frags = manifest.fragment.filter((f) => f.type === type);
    if (frags.length === 0) continue;
    lines.push(`## ${HEADINGS[type]}`, "");
    for (const f of frags) {
      const full = join(root, f.path);
      if (!existsSync(full)) {
        lines.push(`> [missing: ${f.path}]`, "");
        continue;
      }
      lines.push(`### ${f.id}`, "", readFileSync(full, "utf8").trim(), "");
    }
  }
  return lines.join("\n").trim() + "\n";
}

export interface BuildResult {
  written: string[];
}

/** Compile and write all vendor files to the project root. */
export function build(loaded: LoadedManifest, targets = VENDOR_TARGETS): BuildResult {
  const doc = compile(loaded);
  const written: string[] = [];
  for (const t of targets) {
    writeFileSync(join(loaded.root, t.file), doc, "utf8");
    written.push(t.file);
  }
  return { written };
}
