import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { Fragment } from "./types.js";
import type { LoadedManifest } from "./manifest.js";

export interface VendorTarget {
  /** Selector used by `build --target` (e.g. "claude", "cursor"). */
  name: string;
  /** Output filename, relative to project root. */
  file: string;
  label: string;
  /** Vendor-specific preamble rendered above the shared context sections. */
  preamble: (projectName: string) => string;
}

const GENERATED_NOTE =
  "<!-- GENERATED by agenticscope. Do not edit by hand. Edit .scope/ + agenticscope.toml, then run `agenticscope build`. -->";

/** Vendor files agenticscope can compile the .scope/ source into. */
export const VENDOR_TARGETS: VendorTarget[] = [
  {
    name: "claude",
    file: "CLAUDE.md",
    label: "Claude",
    preamble: (n) =>
      `# CLAUDE.md\n\n${GENERATED_NOTE}\n\nProject memory for **${n}**. Treat the rules below as standing instructions.`,
  },
  {
    name: "gemini",
    file: "GEMINI.md",
    label: "Gemini",
    preamble: (n) =>
      `# GEMINI.md\n\n${GENERATED_NOTE}\n\nContext for **${n}**. Apply the rules; use the knowledge as reference.`,
  },
  {
    name: "agents",
    file: "AGENTS.md",
    label: "OpenAI / Codex",
    preamble: (n) =>
      `# AGENTS.md\n\n${GENERATED_NOTE}\n\nAgent instructions for **${n}**, following the AGENTS.md convention.`,
  },
  {
    // .cursorrules is a plain instruction file, not a markdown doc — no H1.
    name: "cursor",
    file: ".cursorrules",
    label: "Cursor",
    preamble: (n) =>
      `You are an AI assistant working on ${n}. Follow these rules and use the context below.\n# (generated by agenticscope — edit .scope/, then run \`agenticscope build\`)`,
  },
];

const ORDER: Fragment["type"][] = ["rule", "persona", "spec", "memory", "knowledge"];
const HEADINGS: Record<Fragment["type"], string> = {
  rule: "Rules (always apply)",
  persona: "Persona",
  spec: "Active specs",
  memory: "Project memory",
  knowledge: "Reference knowledge",
};

/** Render the shared context sections (vendor-agnostic body). */
function renderSections(loaded: LoadedManifest): string {
  const { manifest, root } = loaded;
  const lines: string[] = [];
  for (const type of ORDER) {
    const frags = manifest.fragment.filter((f) => f.type === type);
    if (frags.length === 0) continue;
    lines.push(`## ${HEADINGS[type]}`, "");
    for (const f of frags) {
      const full = join(root, f.path);
      if (!existsSync(full)) {
        lines.push(`> [missing: ${f.path}]`, "");
        continue;
      }
      lines.push(`### ${f.id}`, "", readFileSync(full, "utf8").trim(), "");
    }
  }
  return lines.join("\n").trim();
}

/**
 * Compile a manifest's fragments into a doc for a specific vendor. When no
 * target is given, the default Claude formatting is used (back-compat).
 */
export function compile(loaded: LoadedManifest, target: VendorTarget = VENDOR_TARGETS[0]!): string {
  const name = loaded.manifest.scope.name ?? "this project";
  return `${target.preamble(name)}\n\n${renderSections(loaded)}\n`;
}

export interface BuildResult {
  written: string[];
}

/** Resolve --target names to VendorTargets; throws on an unknown name. */
export function resolveTargets(names?: string[]): VendorTarget[] {
  if (!names || names.length === 0) return VENDOR_TARGETS;
  return names.map((n) => {
    const t = VENDOR_TARGETS.find((v) => v.name === n.toLowerCase());
    if (!t) {
      const valid = VENDOR_TARGETS.map((v) => v.name).join(", ");
      throw new Error(`Unknown vendor target "${n}". Valid targets: ${valid}.`);
    }
    return t;
  });
}

/** Compile and write the given vendor files (all of them by default). */
export function build(loaded: LoadedManifest, targets = VENDOR_TARGETS): BuildResult {
  const written: string[] = [];
  for (const t of targets) {
    writeFileSync(join(loaded.root, t.file), compile(loaded, t), "utf8");
    written.push(t.file);
  }
  return { written };
}

export type VendorStatus = "ok" | "stale" | "missing";
export interface VendorCheck {
  file: string;
  label: string;
  status: VendorStatus;
}

/**
 * Check whether the on-disk vendor files match what `.scope/` would compile to,
 * without writing anything. Lets CI fail when generated files have drifted from
 * their source (`status: "stale"`) or were never built (`status: "missing"`).
 */
export function checkBuild(loaded: LoadedManifest, targets = VENDOR_TARGETS): VendorCheck[] {
  return targets.map((t) => {
    const path = join(loaded.root, t.file);
    const expected = compile(loaded, t);
    let status: VendorStatus;
    if (!existsSync(path)) status = "missing";
    else status = readFileSync(path, "utf8") === expected ? "ok" : "stale";
    return { file: t.file, label: t.label, status };
  });
}
